[versions]
agp = "8.2.2"
kotlin = "2.0.21"
core-ktx = "1.12.0"
wear = "1.3.0"
composeBom = "2025.03.00"
composeMaterial = "1.4.0-beta03"
composeFoundation = "1.4.0-beta03"
composeNavigation = "1.4.0-beta03"
activityCompose = "1.8.2"
coreSplashscreen = "1.0.1"
lifecycleViewModelCompose = "2.7.0"
generativeai = "0.9.0"
kotlinxCoroutines = "1.7.3"
horologist = "0.6.23"
desugar = "2.1.5"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
compose-navigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "composeNavigation" }
wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
material = { group = "androidx.compose.material", name = "material" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
runtime = { group = "androidx.compose.runtime", name = "runtime" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
horologist = { group = "com.google.android.horologist", name = "horologist-compose-material", version.ref = "horologist" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

